# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-11-04 07:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('test_models', '0004_userinfo_cluster_1'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userinfo',
            old_name='avg_time_logged',
            new_name='avg_time_pages',
        ),
    ]
