# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-12-04 05:07
from __future__ import unicode_literals

from django.db import migrations, models
import jsonfield.fields
import picklefield.fields


class Migration(migrations.Migration):

    dependencies = [
        ('test_models', '0005_rename_avg_time_logged'),
    ]

    operations = [
        migrations.CreateModel(
            name='MyStatisticalModel',
            fields=[
                ('id', models.AutoField(
                    auto_created=True, primary_key=True, serialize=False,
                    verbose_name='ID')),
                ('name', models.CharField(
                    max_length=100, unique=True, verbose_name='Name')),
                ('engine_object', picklefield.fields.PickledObjectField(
                    blank=True, editable=False, null=True,
                    verbose_name='Engine Object')),
                ('engine_object_timestamp', models.DateTimeField(
                    blank=True, null=True,
                    verbose_name='Engine Object Timestamp')),
                ('sm_type', models.SmallIntegerField(
                    blank=True, choices=[(0, 'General'), (1, 'Classification'),
                                         (2, 'Regression')],
                    default=0, null=True,
                    verbose_name='Statistical Technique Type')),
                ('metadata', jsonfield.fields.JSONField(
                    blank=True, default={}, null=True,
                    verbose_name='Metadata')),
                ('engine_meta_iterations', models.SmallIntegerField(
                    default=1, verbose_name='Engine Meta Iterations')),
                ('engine_iterations', models.SmallIntegerField(
                    blank=True, null=True,
                    verbose_name='Engine Iterations (Max)')),
                ('results_storage', models.CharField(
                    blank=True, max_length=100, null=True,
                    verbose_name='Results Storage')),
                ('counter', models.IntegerField(
                    blank=True, default=0, null=True,
                    verbose_name='Internal Counter')),
                ('counter_threshold', models.IntegerField(
                    blank=True, null=True,
                    verbose_name='Internal Counter Threshold')),
                ('threshold_actions', models.CharField(
                    blank=True, max_length=200, null=True,
                    verbose_name='Threshold actions')),
            ],
        ),
        migrations.AlterField(
            model_name='userinfo',
            name='avg_time_pages',
            field=models.FloatField(
                blank=True, null=True, verbose_name='Average Time spent on Pages'),
        ),
    ]
