# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-12-20 15:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('test_models', '0010_myunsupervisedlearningtechnique'),
    ]

    operations = [
        migrations.AddField(
            model_name='mystatisticalmodel',
            name='is_inferred',
            field=models.BooleanField(
                default=False, verbose_name='Is Inferred?'),
        ),
        migrations.AddField(
            model_name='mysupervisedlearningtechnique',
            name='is_inferred',
            field=models.BooleanField(
                default=False, verbose_name='Is Inferred?'),
        ),
        migrations.AddField(
            model_name='myunsupervisedlearningtechnique',
            name='is_inferred',
            field=models.BooleanField(
                default=False, verbose_name='Is Inferred?'),
        ),
        migrations.AlterField(
            model_name='mystatisticalmodel',
            name='sm_type',
            field=models.SmallIntegerField(blank=True, choices=[
                (0, 'General / System'),
                (1, 'Classification'),
                (2, 'Regression')],
                default=0, null=True,
                verbose_name='Statistical Technique Type'),
        ),
        migrations.AlterField(
            model_name='mysupervisedlearningtechnique',
            name='sm_type',
            field=models.SmallIntegerField(blank=True, choices=[
                (0, 'General / System'),
                (1, 'Classification'),
                (2, 'Regression')],
                default=0, null=True,
                verbose_name='Statistical Technique Type'),
        ),
        migrations.AlterField(
            model_name='myunsupervisedlearningtechnique',
            name='sm_type',
            field=models.SmallIntegerField(blank=True, choices=[
                (0, 'General / System'),
                (1, 'Classification'),
                (2, 'Regression')],
                default=0, null=True,
                verbose_name='Statistical Technique Type'),
        ),
    ]
