# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-12-22 14:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('test_models', '0011_add_is_inferred_and_minor_tweaks'),
    ]

    def populate_pretraining(apps, schema_editor):
        SFTP = apps.get_model("test_models", "MySFPT")

        SFTP.objects.bulk_create([
            SFTP(content="Buy Viagra Online", is_spam=True),
            SFTP(content="Buy Cialis Online", is_spam=True),
            SFTP(content="Buy Elephant Online", is_spam=True),
            SFTP(content="Loved your Video", is_spam=False),
            SFTP(content="Amazing Video", is_spam=False),
            SFTP(content="I agree with your comment", is_spam=False),
        ])

    def unpopulate_pretraining(apps, schema_editor):
        """
        Nothing to do here (as the table will be deleted)
        """
        pass

    def populate_spammable_mode(apps, schema_editor):
        SpammableModel = apps.get_model("test_models",
                                        "SpammableModel")

        SpammableModel.objects.bulk_create([
            SpammableModel(comment="Hi! Great Article!", is_spam=False),
            SpammableModel(comment="I disagree with you", is_spam=False),
            SpammableModel(comment="Buy a Panda Online!", is_spam=True),
            SpammableModel(comment="Buy a Jiraffe Online!", is_spam=True),
        ])

    def unpopulate_spammable_model(apps, schema_editor):
        """
        Nothing to do here (as the table will be deleted)
        """
        pass

    operations = [
        migrations.CreateModel(
            name='MySFPT',
            fields=[
                ('id', models.AutoField(
                    auto_created=True,
                    primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField(verbose_name='Content')),
                ('is_spam', models.BooleanField(
                    default=False, verbose_name='Is Spam?')),
            ],
            options={
                'verbose_name_plural': 'Spam Filter Pre-Trainings',
                'verbose_name': 'Spam Filter Pre-Training',
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='SpammableModel',
            fields=[
                ('id', models.AutoField(
                    auto_created=True,
                    primary_key=True, serialize=False, verbose_name='ID')),
                ('is_spam', models.BooleanField(
                    default=False,
                    help_text='If the object is Spam',
                    verbose_name='Is Spam?')),
                ('is_misclassified', models.BooleanField(
                    default=False,
                    help_text=('If the object has been misclassified by '
                               'the Spam Filter'),
                    verbose_name='Is Misclassified?')),
                ('is_revised', models.BooleanField(
                    default=False,
                    help_text=('If the object classification has been revised '
                               'by a Human'),
                    verbose_name='Is Revised?')),
                ('comment', models.TextField(
                    verbose_name='Comment')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.RunPython(
            populate_pretraining, unpopulate_pretraining
        ),
        migrations.RunPython(
            populate_spammable_mode, unpopulate_spammable_model
        ),
    ]
