# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-12-29 15:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('test_models', '0012_mysfpt_spammablemodel'),
    ]

    operations = [
        migrations.AlterField(
            model_name='spammablemodel',
            name='is_spam',
            field=models.NullBooleanField(
                help_text='If the object is Spam', verbose_name='Is Spam?'),
        ),
    ]
