# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2018-01-10 17:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('test_models', '0013_nullboolean_for_sp_is_spam'),
    ]

    operations = [
        migrations.AddField(
            model_name='mysupervisedlearningtechnique',
            name='cv_folds',
            field=models.SmallIntegerField(
                blank=True,
                help_text='Quantity of Folds to be used in Cross Validation',
                null=True, verbose_name='Cross Validation Folds'),
        ),
        migrations.AddField(
            model_name='mysupervisedlearningtechnique',
            name='cv_is_enabled',
            field=models.BooleanField(
                default=True,
                help_text='Enable Cross Validation',
                verbose_name='Cross Validation is Enabled?'),
        ),
        migrations.AddField(
            model_name='mysupervisedlearningtechnique',
            name='cv_metric',
            field=models.CharField(
                blank=True,
                help_text='Metric to be evaluated in Cross Validation',
                max_length=20,
                null=True,
                verbose_name='Cross Validation Metric'),
        ),
        migrations.AddField(
            model_name='mysupervisedlearningtechnique',
            name='pretraining',
            field=models.CharField(
                blank=True,
                help_text=('Django Model containing the pre-training dataset '
                           'in the"app_label.model" format, i.e. '
                           '"examples.SFPTEnron"'),
                max_length=100,
                null=True,
                verbose_name='Pre-Training dataset'),
        ),
        migrations.AlterField(
            model_name='mystatisticalmodel',
            name='sm_type',
            field=models.SmallIntegerField(
                blank=True,
                choices=[(0, 'General'), (1, 'Classification'),
                         (2, 'Regression')],
                default=0,
                null=True,
                verbose_name='Statistical Technique Type'),
        ),
        migrations.AlterField(
            model_name='mysupervisedlearningtechnique',
            name='sm_type',
            field=models.SmallIntegerField(
                blank=True,
                choices=[(0, 'General'), (1, 'Classification'),
                         (2, 'Regression')],
                default=0,
                null=True,
                verbose_name='Statistical Technique Type'),
        ),
        migrations.AlterField(
            model_name='myunsupervisedlearningtechnique',
            name='sm_type',
            field=models.SmallIntegerField(
                blank=True,
                choices=[(0, 'General'), (1, 'Classification'),
                         (2, 'Regression')],
                default=0,
                null=True,
                verbose_name='Statistical Technique Type'),
        ),
    ]
