# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-11-07 04:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('examples', '0009_rename_avg_time_logged'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userinfo',
            name='avg_time_pages',
            field=models.FloatField(blank=True, default=0, null=True, verbose_name='Average Time on Pages'),
        ),
        migrations.AlterField(
            model_name='userinfo',
            name='avg_time_pages_a',
            field=models.FloatField(blank=True, default=0, null=True, verbose_name='Average Time on Pages of type A'),
        ),
        migrations.AlterField(
            model_name='userinfo',
            name='sex',
            field=models.SmallIntegerField(blank=True, choices=[(0, 'M'), (1, 'F')], null=True, verbose_name='Sex'),
        ),
        migrations.AlterField(
            model_name='userinfo',
            name='visits_pages',
            field=models.IntegerField(default=0, verbose_name='Visits on Pages (Total)'),
        ),
        migrations.AlterField(
            model_name='userinfo',
            name='visits_pages_a',
            field=models.IntegerField(default=0, verbose_name='Visits on Pages A'),
        ),
    ]
