# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-11-09 08:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('examples', '0010_tweaks_on_userinfo'),
    ]

    operations = [
        migrations.AddField(
            model_name='userinfo',
            name='avg_time_pages_b',
            field=models.FloatField(
                blank=True, default=0, null=True,
                verbose_name='Average Time on Pages of type B'),
        ),
        migrations.AddField(
            model_name='userinfo',
            name='avg_time_pages_c',
            field=models.FloatField(
                blank=True, default=0, null=True,
                verbose_name='Average Time on Pages of type C'),
        ),
        migrations.AddField(
            model_name='userinfo',
            name='avg_time_pages_d',
            field=models.FloatField(
                blank=True, default=0, null=True,
                verbose_name='Average Time on Pages of type D'),
        ),
        migrations.AddField(
            model_name='userinfo',
            name='avg_time_pages_e',
            field=models.FloatField(
                blank=True, default=0, null=True,
                verbose_name='Average Time on Pages of type E'),
        ),
        migrations.AddField(
            model_name='userinfo',
            name='avg_time_pages_f',
            field=models.FloatField(
                blank=True, default=0, null=True,
                verbose_name='Average Time on Pages of type F'),
        ),
        migrations.AddField(
            model_name='userinfo',
            name='avg_time_pages_g',
            field=models.FloatField(
                blank=True, default=0, null=True,
                verbose_name='Average Time on Pages of type G'),
        ),
        migrations.AddField(
            model_name='userinfo',
            name='avg_time_pages_h',
            field=models.FloatField(
                blank=True, default=0, null=True,
                verbose_name='Average Time on Pages of type H'),
        ),
        migrations.AddField(
            model_name='userinfo',
            name='avg_time_pages_i',
            field=models.FloatField(
                blank=True, default=0, null=True,
                verbose_name='Average Time on Pages of type I'),
        ),
        migrations.AddField(
            model_name='userinfo',
            name='avg_time_pages_j',
            field=models.FloatField(
                blank=True, default=0, null=True,
                verbose_name='Average Time on Pages of type J'),
        ),
        migrations.AddField(
            model_name='userinfo',
            name='visits_pages_b',
            field=models.IntegerField(
                default=0, verbose_name='Visits on Pages of type B'),
        ),
        migrations.AddField(
            model_name='userinfo',
            name='visits_pages_c',
            field=models.IntegerField(
                default=0, verbose_name='Visits on Pages of type C'),
        ),
        migrations.AddField(
            model_name='userinfo',
            name='visits_pages_d',
            field=models.IntegerField(
                default=0, verbose_name='Visits on Pages of type D'),
        ),
        migrations.AddField(
            model_name='userinfo',
            name='visits_pages_e',
            field=models.IntegerField(
                default=0, verbose_name='Visits on Pages of type E'),
        ),
        migrations.AddField(
            model_name='userinfo',
            name='visits_pages_f',
            field=models.IntegerField(
                default=0, verbose_name='Visits on Pages of type F'),
        ),
        migrations.AddField(
            model_name='userinfo',
            name='visits_pages_g',
            field=models.IntegerField(
                default=0, verbose_name='Visits on Pages of type G'),
        ),
        migrations.AddField(
            model_name='userinfo',
            name='visits_pages_h',
            field=models.IntegerField(
                default=0, verbose_name='Visits on Pages of type H'),
        ),
        migrations.AddField(
            model_name='userinfo',
            name='visits_pages_i',
            field=models.IntegerField(
                default=0, verbose_name='Visits on Pages of type I'),
        ),
        migrations.AddField(
            model_name='userinfo',
            name='visits_pages_j',
            field=models.IntegerField(
                default=0, verbose_name='Visits on Pages of type J'),
        ),
        migrations.AlterField(
            model_name='userinfo',
            name='visits_pages_a',
            field=models.IntegerField(
                default=0, verbose_name='Visits on Pages of type A'),
        ),
    ]
