# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-11-25 07:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('examples', '0012_update_clustering_bn'),
    ]

    operations = [
        migrations.CreateModel(
            name='CommentOfMySite',
            fields=[
                ('id', models.AutoField(
                    auto_created=True,
                    primary_key=True, serialize=False,
                    verbose_name='ID')
                 ),
                ('is_spam', models.BooleanField(
                    default=False,
                    help_text='If the object is Spam',
                    verbose_name='Is Spam?')
                 ),
                ('is_misclassified', models.BooleanField(
                    default=False,
                    help_text=('If the object has been misclassified by '
                               'the Spam Filter'),
                    verbose_name='Is Misclassified?')
                 ),
                ('is_revised', models.BooleanField(
                    default=False,
                    help_text=('If the object classification has been revised '
                               'by a Human'),
                    verbose_name='Is Revised?')
                 ),
                ('comment', models.TextField(
                    verbose_name='Comment')
                 ),
                ('user_id', models.SmallIntegerField(
                    verbose_name='User ID')
                 ),
            ],
            options={
                'verbose_name': 'Comment of my Site',
                'verbose_name_plural': 'Comments of my Site',
            },
        ),
    ]
