# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-11-27 08:16
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('examples', '0013_commentofmysite'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='userinfo',
            options={'verbose_name': 'User Info', 'verbose_name_plural': 'Users Infos'},
        ),
    ]
