# Generated by Django 3.1.5 on 2021-01-15 09:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='DataColumn',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('object_id', models.PositiveIntegerField()),
                ('ref_column', models.CharField(max_length=100, verbose_name='Column / Attribute')),
                ('is_categorical', models.BooleanField(default=False, verbose_name='Is Categorical?')),
                ('monotonic_cst', models.SmallIntegerField(choices=[(-1, '-1'), (0, '0'), (1, '1')], default=0, verbose_name='Monotonic Constraint')),
                ('position', models.SmallIntegerField(blank=True, null=True, verbose_name='Position')),
                ('content_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype')),
                ('ref_model', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ai_base_datacolumns', to='contenttypes.contenttype', verbose_name='Django Model')),
            ],
            options={
                'verbose_name': 'Data Column',
                'verbose_name_plural': 'Data Columns',
                'unique_together': {('content_type', 'object_id', 'position'), ('content_type', 'object_id', 'ref_model', 'ref_column')},
            },
        ),
    ]
