# Generated by Django 4.2 on 2023-04-13 04:44

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("ai_base", "0003_engineobjectmodel_default_metadata"),
    ]

    operations = [
        migrations.AlterField(
            model_name="learningtechnique",
            name="id",
            field=models.BigAutoField(
                auto_created=True,
                primary_key=True,
                serialize=False,
                verbose_name="ID",
            ),
        ),
    ]
