# Generated by Django 3.1.5 on 2021-03-03 10:19

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("supervised_learning", "0002_svr"),
    ]

    operations = [
        migrations.AlterField(
            model_name="supervisedlearningtechnique",
            name="learning_target",
            field=models.CharField(
                blank=True,
                help_text="Field in the Data Model containing the targets for Learning",
                max_length=50,
                null=True,
                verbose_name="Learning Targets",
            ),
        ),
    ]
