# Generated by Django 3.1.5 on 2021-03-04 09:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('supervised_learning', '0004_supervisedlearningimputer'),
    ]

    operations = [
        migrations.CreateModel(
            name='IntrospectionImputer',
            fields=[
                ('supervisedlearningimputer_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='supervised_learning.supervisedlearningimputer')),
            ],
            options={
                'abstract': False,
            },
            bases=('supervised_learning.supervisedlearningimputer',),
        ),
    ]
