# Generated by Django 3.1.5 on 2021-03-05 21:36

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("ai_base", "0003_engineobjectmodel_default_metadata"),
        ("supervised_learning", "0006_svmimputer"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="HGBTree",
            new_name="HGBTreeClassifier",
        ),
    ]
