# Generated by Django 3.2.8 on 2021-10-19 03:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('supervised_learning', '0009_hgbtreeimputer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hgbtreeregressor',
            name='loss',
            field=models.CharField(blank=True, choices=[('squared_error', 'Squarred Error'), ('least_absolute_deviation', 'Least Absolute Deviation'), ('poisson', 'Poisson'), ('absolute_error', 'Absolute Error')], default='squarred_error', help_text='The loss function to be used in the boosting process. If none is given, least_squares will be used.', max_length=50, null=True, verbose_name='Loss function'),
        ),
    ]
