# Generated by Django 4.2 on 2023-05-03 19:00

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("supervised_learning", "0012_oneclasssvc"),
    ]

    operations = [
        migrations.AlterField(
            model_name="oneclasssvc",
            name="nu",
            field=models.FloatField(
                blank=True,
                default=0.5,
                help_text="An upper bound on the fraction of training errors and a lower bound of the fraction of support vectors. Should be in the interval (0, 1]. By default 0.5 will be taken.",
                null=True,
                verbose_name="Nu",
            ),
        ),
    ]
