# Generated by Django 4.2.3 on 2023-07-26 03:56

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("supervised_learning", "0013_alter_oneclasssvc_nu"),
    ]

    operations = [
        migrations.AlterField(
            model_name="hgbtreeclassifier",
            name="loss",
            field=models.CharField(
                blank=True,
                choices=[("log_loss", "Log Loss")],
                default="log_loss",
                help_text="The loss function to be used in the boosting process. If none is given, auto will be used.",
                max_length=50,
                null=True,
                verbose_name="Loss function",
            ),
        ),
    ]
